# Generated by Django 3.1.7 on 2021-06-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('descripcion', models.CharField(default='', max_length=200, null=True)),
                ('fuente', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='deportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('descripcion', models.CharField(default='', max_length=200, null=True)),
                ('fuente', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='nacionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, null=True)),
                ('descripcion', models.CharField(default='', max_length=200, null=True)),
                ('fuente', models.CharField(default='', max_length=200, null=True)),
                ('fecha', models.CharField(default='', max_length=200, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
    ]
